name: wf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.3.1
  - notebook=7.0.6
  - jupyterlab=4.0.9
  - xlsxwriter=3.1.9
  - tqdm=4.66.1
  - oyaml=1.0
  - ipykernel=6.25
  - pip:
    - tensorflow==2.5
    - tensorflow-addons==0.13
    - tensorflow-probability==0.11
    - tensorboard==2.8
    - protobuf==3.19.4
    - matplotlib==3.4 
    - einops=0.7.0
    - cloudpickle==1.3