dataset: Sup-203
data_size: 384
DL_gen: false
DL_experiment_dir: output/GAN-238
n_per_epoch: 10000
gen_noise: 0.1
DL_LDM: false
DDIM: false
infer_steps: 25
n_echoes: 3
TE1: 0.0013
dTE: 0.0021
field: 1.5
out_vars: WF
G_model: U-Net
n_G_filters: 36
batch_size: 8
epochs: 100
epoch_decay: 100
epoch_ckpt: 10
lr: 0.0001
beta_1: 0.9
beta_2: 0.9999
R2_TV_weight: 0.0
FM_TV_weight: 0.0
R2_L1_weight: 0.0
FM_L1_weight: 0.0
D1_SelfAttention: false
D2_SelfAttention: true
D3_SelfAttention: true
